### ISSUE TITLE
does stop called when session termination is about to happen??

### ISSUE THREAD

**Issue by asolanki-in** [krmahadevan/demo-node#1]
I tried this code but looks stop didn't get called
I am using selenium 4.8.3 jar

**Comment by krmahadevan** [comment]
@asolanki-in - Here's why that happens

* When you a `driver.quit()` this ends up eventually landing in `org.openqa.selenium.grid.node.local.LocalNode#executeWebDriverCommand` 
* The `executeWebDriverCommand()` within `LocalNode` internally invokes the `stop()` method that resides within `LocalNode`
* So the call is never getting to `stop()` that is overloaded within your decorated node.

The current form of the selenium grid doesn't allow the stop method to be invoked when we resort to composition. I would suggest that you file an enhancement defect with the selenium project, so that this can be discussed and then addressed.

**Comment by asolanki-in** [comment]
What about this PR?

[11718](https://github.com/SeleniumHQ/selenium/pull/11718)

Not sure but I think this PR was about this???

@krmahadevan

**Comment by asolanki-in** [comment]
Can you also help to extend LocalNode itself??

I am kind of new to selenium and java

Basically I am implementing a session time duration of a automation in success and timeout cases.

**Comment by krmahadevan** [comment]
Sure that can be done too. In that case you would need to extend LocalNode and also build a similar method to LocalNodeFactory that would instantiate the child class of LocalNode.

**Comment by krmahadevan** [comment]
You can plug your implementation within executeWebDriverCommand method also and that should do what you need in todays world.

**Comment by asolanki-in** [comment]
> executeWebDriverCommand


So when a session is timeout due to any reason will this function will be called???

**Comment by krmahadevan** [comment]
To the best of my knowledge this will get called when you invoke a `driver.quit()`. The timedout sessions are auto invoked via the Guava cache and there's no mechanism in the current implementation that would allow you to be notified of, when there are session timeouts in either of the two modes viz.,
* When you compose a decorated node using a local node (or)
* When you extend the Local Node.

I think you should perhaps log a ticket that specifically asks for a support for your usecase, when customising the nodes.
